sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t uphillian/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true uphillian/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-896380160423"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
